server:
  port: 8083  # for driver, 8083 for rider, 8084 for dispatch, 8085 for ws (pick unique)

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ridedb
    username: ride
    password: ridepass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "+d23SXmOtA6cmu+yI1W8ejc5kp9MOM9QPkNwvP5XFw8GF0+S1o7G4/bbefO6Bit9L/1IThtDCI/cRewO3cfFWA=="
  expirationMs: 3600000  # 1h